---
title: "model_definition.rmd"
output: html_document
---

``` {r}
library(ggplot2)
library(reshape2)
library(plyr)
library(reticulate)

model <- import("libcbm.model.model_definition.model")
output_processor <- import("libcbm.model.model_definition.output_processor")
model_variables <- import("libcbm.model.model_definition.model_variables")
```

``` {r}
pool_def = list(
  "Input",
  "WoodyBiomass",
  "Foliage",
  "SlowDOM",
  "MediumDOM",
  "FastDOM",
  "CO2",
  "Products"
)
```

``` {r}
flux_indicators = c(
    dict(
        name="NPP",
        process="GrowthAndMortality",
        source_pools=list(
            "Input",
            "Foliage"
        ),
        sink_pools=list(
            "WoodyBiomass",
            "Foliage",
            "FastDOM"
        )
    ),
    dict(
        name="DecayEmissions",
        process="Decay",
        source_pools=list(
            "SlowDOM",
            "MediumDOM",
            "FastDOM"
        ),
        sink_pools=list(
            "CO2"
        )
    ),
    dict(
        name="DisturbanceEmissions",
        process="Disturbance",
        source_pools=list(
            "WoodyBiomass",
            "Foliage",
            "SlowDOM",
            "MediumDOM",
            "FastDOM"
        ),
        sink_pools=list(
            "CO2"
        )
    ),
    dict(
        name="HarvestProduction",
        process="Disturbance",
        source_pools=list(
            "WoodyBiomass",
            "Foliage",
            "MediumDOM"
        ),
        sink_pools=list(
            "Products"
        )
    )
)
```

``` {r}
weibull_cumulative <- function(x, k=2.3, y=1) {
    c = (x/y) ^ k
    return(1 - exp(-c))
}

create_npp_matrix <- function(model, age) {
    # creates NPP flows based on an age passed to the cumulative weibull distribution
    n_stands = length(age)
    npp = matrix(weibull_cumulative((age+1)/100.0) - weibull_cumulative(age/100.0))
    model$matrix_ops$create_operation(
        name="growth",
        op_process_name="GrowthAndMortality",
        op_data=data.frame(
            Input.WoodyBiomass=npp,
            Input.Foliage=npp/10.0
        )
    )
}
```

``` {r}

create_mortality_matrix <- function(model, n_stands) {

    model$matrix_ops$create_operation(
        name="mortality",
        op_process_name="GrowthAndMortality",
        op_data=data.frame(
            WoodyBiomass.WoodyBiomass=1.0,
            WoodyBiomass.MediumDOM=0.01,
            Foliage.Foliage=1.0,
            Foliage.FastDOM=0.95
        )
    )

}
```

``` {r}
create_decay_matrix <- function(model, n_stands) {
    model$matrix_ops$create_operation(
        name="decay",
        op_process_name="Decay",
        op_data=data.frame(
            SlowDOM.SlowDOM=0.97,
            SlowDOM.CO2=0.03,

            MediumDOM.MediumDOM=0.85,
            MediumDOM.SlowDOM=0.10,
            MediumDOM.CO2=0.05,

            FastDOM.FastDOM=0.65,
            FastDOM.MediumDOM=0.25,
            FastDOM.CO2=0.10
        )
    )
}
```

``` {r}
disturbance_type_ids = c(
    none=0L,
    fire=1L,
    harvest=2L
)

create_disturbance_matrix <- function(model, disturbance_types) {

    no_disturbance <- data.frame(
        parameters.disturbance_type=0L,
        # 100% of biomass is retained
        WoodyBiomass.WoodyBiomass=1.0,
        Foliage.Foliage=1.0
    )

    fire_matrix <- data.frame(
        parameters.disturbance_type=1L,
        WoodyBiomass.WoodyBiomass=0.0,
        WoodyBiomass.CO2=0.85,
        WoodyBiomass.MediumDOM=0.15,
        Foliage.Foliage=0.0,
        Foliage.CO2=0.95,
        Foliage.FastDOM=0.05
    )
    harvest_matrix <- data.frame(
        parameters.disturbance_type=2L,
        WoodyBiomass.WoodyBiomass=0.0,
        WoodyBiomass.Products=0.85,
        WoodyBiomass.MediumDOM=0.15,
        Foliage.Foliage=0.0,
        Foliage.FastDOM=1.0
    )
    all_dms <- rbind.fill(no_disturbance, fire_matrix, harvest_matrix)
    # since the result has differing columns, fill the empty entries
    all_dms[is.na(all_dms)] <- 0.0
    # [] column name format indicates this matrix data applies
    # to cbm_vars.parameters.disturabance_type where the value
    # is 0.  This means the appropriate DM value is selected based
    # on the current value for disturbance type at each step
    names(all_dms)[1] <- "[parameters.disturbance_type]"

    model$matrix_ops$create_operation(
        name="disturbance", op_process_name="Disturbance", op_data=all_dms
    )
}

```

``` {r}

with(model$initialize(pool_def, flux_indicators) %as% cbm_model, {

    out_processor = output_processor$ModelOutputProcessor()
    n_stands = 200L

    model_vars <- model_variables$ModelVariables$from_pandas(
      dict(
        pools=data.frame(
          matrix(
            0.0,
            nrow=n_stands,
            ncol=length(cbm_model$pool_names),
            dimnames=list(NULL, cbm_model$pool_names)
          )
        ),
        flux=data.frame(
          matrix(
            0.0,
            nrow=n_stands,
            ncol=length(cbm_model$flux_names),
            dimnames=list(NULL, cbm_model$flux_names)
          )
        ),
        state=data.frame(
          matrix(1L, nrow=n_stands, ncol=1, dimnames=list(NULL, c("enabled")))
        ),
        parameters=data.frame(
            matrix(1L, nrow=n_stands, ncol=1, dimnames=list(NULL, c("disturbance_type")))
        )
      )
    )

    create_decay_matrix(cbm_model)
    create_disturbance_matrix(cbm_model)
    create_mortality_matrix(cbm_model)

    model_vars["pools"]["Input"]$assign(1.0)

    stand_age = rep(0L, n_stands)

    timesteps <- 0:300L
    for(t in timesteps) {
        print(t)
        create_npp_matrix(cbm_model, stand_age)
        # add some simplistic disturbance scheduling
        disturbance_types = sample(
          c(0L,1L,2L),
          n_stands,
          replace=TRUE,
          prob=c(1, 0, 0)
        )
        # assign parameters.disturbance_type to trigger matrix
        # selection in the compute step
        model_vars["parameters"]["disturbance_type"]$assign(disturbance_types)
        # reset flux at start of every time step
        model_vars["flux"]$zero()

        # enabled array can be used to disable(0)/enable(1)
        # dynamics per index
        model_vars["state"]["enabled"]$assign(
          rep(1L, n_stands))

        cbm_model$compute(
            model_vars,
            cbm_model$matrix_ops$get_operations(
                c("disturbance", "growth", "mortality", "decay"), model_vars
            )
        )

        out_processor$append_results(t, model_vars)
        stand_age[disturbance_types != 0] = 0
        stand_age = stand_age + 1
    }
})
```

```{r}
results <- out_processor$get_results()$to_pandas()

aggregated_age = aggregate(
  results$pools$WoodyBiomass, by=list(timestep=results$state$timestep), FUN=mean
)
colnames(aggregated_age)= c("timestep", "age")
plot(aggregated_age$timestep, aggregated_age$age)

```